language: android

android:
  components:
    - tools
    - platform-tools

jdk:
  - oraclejdk8

before_install:
  # Install SDK license so Android Gradle plugin can install dependencies.
  - mkdir "$ANDROID_HOME/licenses" || true
  - echo "d56f5187479451eabf01fb78af6dfcb131a6481e" > "$ANDROID_HOME/licenses/android-sdk-license"

script:
  - ./gradlew test
  - (cd plugin/ && ./gradlew check)

branches:
  except:
    - gh-pages

notifications:
  email: false

cache:
  directories:
    - $HOME/.m2
