-keep public class * extends com.jaynewstrom.json.runtime.JsonSerializerFactory { public <init>(); }
-keep public class * extends com.jaynewstrom.json.runtime.JsonDeserializerFactory { public <init>(); }
